### ISSUE TITLE
Modifying script to display only the currrently active window

### ISSUE THREAD

**Issue by romanidrip** [melangue/bspwm-window-titles#1]
Firstly - awesome script, it works perfectly with Polybar and setup is easy too.

One thing I wish though is if it didn't show every window, but just the currently active one. I looked at bspwm_window_titles.sh and I see it highlights the currently active window with brackets (so it is detectable), I just can't figure out how to modify it to **only** display the current window.

Even though you even commented almost every single line :cry:  I still can't get it.

Would you be able to modify this to do so? If not, that's OK too, it doesn't bother me that much.

Thx again for the awesome script

**Comment by nicnic-cc** [comment]
Hey, thanks for the kind words.

Why don't you use built-in [xwindow module](https://github.com/polybar/polybar/wiki/Module:-xwindow) of polybar if you just need to show the currently active window? Afaik it does just that.

If you still want to use this script, I can give you a little tip - look at the 61 line - this is the part where it's adding each window name to a variable in a loop. If you modify that if statement to add window names only if it's active - then that will get you what you need :)

**Comment by romanidrip** [comment]
Oh, awesome, should've checked Polybar modules first, but I didn't see it from Google.

Thanks for the help, will probably use the xwindow module then :+1:  :)
